# Linter Options
options:
  merge-default-rules: false

# Rule Configuration
rules:
  extends-before-mixins: 1
  extends-before-declarations: 1
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 2
    -
      size: 4
  no-invalid-hex: 2
  no-vendor-prefixes: 2
  one-declaration-per-line: 2
  zero-unit: 2
